# Usa uma imagem do Node.js como base
FROM node:18

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos do projeto para dentro do container
COPY . .

# Instala as dependências do sistema para rodar o Puppeteer
RUN apt-get update && apt-get install -y \
  libx11-xcb1 \
  libasound2 \
  libnss3 \
  libxss1 \
  libappindicator3-1 \
  libatk-bridge2.0-0 \
  libgbm-dev \
  && rm -rf /var/lib/apt/lists/*

# Instala as dependências do projeto
RUN npm install

# Define a variável de ambiente para o Puppeteer ignorar a instalação do Chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable

# Define o comando para rodar o bot
CMD ["node", "monitor.js"]