# Usa a imagem oficial do Playwright com Node.js
FROM mcr.microsoft.com/playwright:v1.50.1-focal

# Define o diretório de trabalho no container
WORKDIR /app

# Copia os arquivos do projeto para dentro do container
COPY . .

# Instala as dependências do projeto
RUN npm install

# Instala os navegadores necessários para o Playwright
RUN npx playwright install chromium

# Define o comando para rodar o bot
CMD ["node", "monitor.js"]